### PR TITLE
Fixed no news found bug

### PR DESCRIPTION
**Pull request by decaffeinatedcoffee**
The filter with en as lang was making 0 news as result so i make it filter by the country langs.

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
No @decaffeinatedcoffee, it is happened because my limit for API request reached

**Comment by decaffeinatedcoffee** [comment]
but theres no limit error, only 0 articles found, also with this edit its working 100%, also when i changed the country var to USA it worked with the fixed en filter

**Comment by codemaniac-sahil** [comment]
would you please check again the website as it is working fine

**Comment by decaffeinatedcoffee** [comment]
hm ok

**Comment by decaffeinatedcoffee** [comment]
ye, with my edit/with fixed lang
image
image

**Comment by codemaniac-sahil** [comment]
Okay I am Merging your branch

**Comment by codemaniac-sahil** [comment]
connect with me in discord for upcoming projects 
codemaniac_sahil#3664

**Pull request merged**
